In [3]:
import numpy as np

In [4]:
# Checking NumPy Version 
print(np.__version__)

1.26.0


In [5]:
# Creating NumPy Arrays 
arr = np.array(42)
# check type
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
42


In [6]:
# 1-D Arrays:
arr = np.array([23,33,44,55])
print(arr)
# Check Number of Dimensions
print(arr.ndim)

[23 33 44 55]
1


In [7]:
# 2-D Arrays
arr = np.array([[3,4,5,6],[6,7,8,9]])
print(arr)
# Check Number of Dimensions
print(arr.ndim)

[[3 4 5 6]
 [6 7 8 9]]
2


In [8]:
# 3-D Arrays:
arr = np.array([[[3,4,5,6],[6,7,8,9]],[[5,6,7,8],[5,6,7,8]]])
print(arr)

[[[3 4 5 6]
  [6 7 8 9]]

 [[5 6 7 8]
  [5 6 7 8]]]


In [9]:
# Check Number of Dimensions
print(arr.ndim)

3


In [10]:
# Higher-Dimensional Arrays :
arr_nd = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]])
print(arr_nd)
# Check Number of Dimensions
print(arr_nd.ndim)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
4


In [11]:
# Basic Indexing
# index                    0  1  2  3  4
arr =            np.array([1, 2, 3, 4, 5])
# Negative Index          -5 -4 -3 -2 -1
print(arr[0])  # Access the first element (1)
print(arr[2])  # Access the third element (3)
# Negative Index 
print(arr[-1])  # Access the last element (5)
print(arr[-2])  # Access the second-to-last element (4)

1
3
5
4


In [12]:
# Multidimensional Array Indexing 
arr_2d = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])

print(arr_2d[0, 1]) # Access element at row 1, column 2 (6)

# Using a single tuple of indices
indices = (1, 2)
print(arr_2d[indices])  # Access the same element (6)

2
6


In [13]:
# Slicing in Multidimensional Arrays :
print(arr_2d[:,1]) # # Access the second column ([2, 5])
print(arr_2d[0, :])  # Access the first row ([1, 2, 3])

[2 5 8]
[1 2 3]


In [14]:
# Fancy Indexing :
row_indices = np.array([0, 0])
col_indices = np.array([1, 1])
selected_elements = arr_2d[row_indices, col_indices]
print(selected_elements)

[2 2]


In [15]:
# Ellipsis (…) Indexing :
arr_3d = np.array([[[1, 2,11], [3, 4,12]], [[5, 6,13], [7, 8,14]]])
print(arr_3d[...,0])  # Access the first element along the third dimension ([[1, 3], [5, 7]])

[[1 3]
 [5 7]]


In [16]:
# Creating Arrays With a Defined Data Type
arr = np.array([1, 2, 3, 4, 5], dtype='float')
print(arr)
arr = np.array([1, 2, 3, 4, 5], dtype='str')
print(arr)

[1. 2. 3. 4. 5.]
['1' '2' '3' '4' '5']


In [17]:
# Converting Data Type on Existing Arrays 
arr = arr.astype('int')
print(arr)

[1 2 3 4 5]


In [18]:
# NumPy Array Shape :
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)  # (2, 3), indicating a 2x3 array

(2, 3)


In [19]:
# NumPy Array Reshaping :
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(6,1)  # Reshape into a 2x3 array
print(reshaped)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [20]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
for item in arr:
    print(item)

1
2
3
4
5
6
7


In [23]:
# NumPy Joining Arrays
arr11 = np.array([1, 2, 3])
arr22 = np.array([4, 5, 6])
result = np.concatenate((arr11, arr22))  # Concatenate along the first axis (axis 0)
print(result)

[1 2 3 4 5 6]


In [29]:
# NumPy Splitting Arrays
arr = np.array([1, 2, 3, 4, 5, 6])
sub_arrays = np.array_split(arr, 3)  # Split into 3 equal-sized sub-arrays
print(sub_arrays)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [32]:
# NumPy Searching Arrays
arr = np.array([1, 2, 3, 4, 5])
indexes = np.where(arr == 3)  # Find the index where value is 3
print(indexes)

(array([2]),)


In [34]:
# NumPy Sorting Arrays
arr = np.array([3, 1, 2, 4, 5])
arr.sort()  # Sort in ascending order
print(arr)

[1 2 3 4 5]


In [37]:
arr = np.array([1, 2, 3, 4, 5])
condition = arr > 2
filtered = arr[condition]  # Select elements greater than 2
print(filtered)

[3 4 5]


In [38]:
# Creating a DataFrame from a NumPy Array:
import pandas as pd
# Create a NumPy array
data = np.array([
    ['Alice', 25, 'New York'],
    ['Bob', 30, 'San Francisco'],
    ['Charlie', 35, 'Los Angeles']
])
# Create a DataFrame from the NumPy array
df = pd.DataFrame(data, columns=['Name', 'Age', 'City'])
# Display the DataFrame
print(df)

      Name Age           City
0    Alice  25       New York
1      Bob  30  San Francisco
2  Charlie  35    Los Angeles
